let test = [
	{
		id: 16,
		link: 'https://learn.purpleschool.ru/public/product/170b4b68-4ba2-4eb0-a02b-ce3b7da8f0eb/tariffs',
		alias: 'kubernetes-helm',
		title: 'Kubernetes и Helm',
		shortTitle: 'Kubernetes и Helm',
		metaTitle: 'Онлайн курс Kubernetes и Helm',
		metaDescription: 'Полный курс по работе Kubernetes и созданию Helm Charts',
		subTitle: 'Полный курс по работе Kubernetes и созданию Helm Charts',
		description:
			'<p>В этом курсе мы изучим Kubernetes и Helm, и развернём на нём полноценное приложение. Этот курс подойдёт как backend разработчикам, которые хотят научиться разворачивать свои приложения в Kubernetes и использовать Helm charts, так и системным администраторам, которые развиваются в направлении DevOps. </p><p>Курс будет сфокусирован на практике работы с Kubernetes и реальных сценариях использования, которые вам пригодятся в ежедневной работе. При этом мы будем детально разбирать его устройство, чтобы понимать как он работает под капотом и что происходит в кластере при выполнении тех или иных команд. Так же в курсе присутствуют дополнительные упражнения, которые помогут вам попрактиковаться в работе с Kubernetes.</p>',
		image: 'https://cdn-bucket.hb.bizmrg.com/purple-images/profile-images/5413f602-3fbc-4461-825c-efeb1acff221.jpg',
		video: 'd17fe54f-b570-4169-b9d1-f6c7c0ab12a5',
		skills: [
			'Работать с kubectl',
			'Понимать механику работы кластера Kubernetes',
			'Писать конфигурации для выкладки приложений',
			'Работать с YML синтаксисом',
			'Работать с Pod, Deployment, Services, ConfigMap и другими объектами',
			'Выкладывать полноценные приложения на кластер',
			'Работать с сетью и хранением данных',
			'Шифровать секреты',
			'Писать Helm Charts',
			'Управлять релизами приложения через Helm',
			'Работать с Helm репозиторием',
		],
		requirements: ['Знание основ Linux', 'Будет плюсом знание Docker'],
		teacherId: 1,
		status: 'published',
		udemyRating: 5,
		createdAt: '2023-10-27T10:33:56.666Z',
		updatedAt: '2024-02-19T14:31:46.280Z',
		courseId: null,
		telegramChannelId: '0',
		telegramThreadName: null,
		tariff: 'basic',
		price: 0,
		oldPrice: 0,
		creditPrice: null,
		discountEndDate: null,
		length: 10,
		tests: 13,
		exercises: 8,
		order: 2,
		hasConsultaion: false,
		demoVideo: '2b284f69-7271-49ed-aa10-62f5d502343f',
		dzenclassSheet: 'Kubernetes и Helm (170b4b68-4ba2-4eb0-a02b-ce3b7da8f0eb)',
		discordRoleId: null,
		discordCategoryId: null,
		discordChannelsId: [],
		techs: ['Kubernetes', 'Helm', 'Helm Charts', 'Helm Secrets'],
		isOnSite: true,
		courseOnDirection: [
			{ courseId: 16, directionId: 3, direction: { id: 3, name: 'DevOps' } },
			{ courseId: 16, directionId: 2, direction: { id: 2, name: 'Backend' } },
		],
		tariffs: [
			{
				id: 42,
				name: 'С наставником',
				enName: 'With mentor',
				type: 'mentor',
				price: 8990,
				oldPrice: 16000,
				creditPrice: 4495,
				lengthInMonth: 2,
				videoUuid: 'a93c9aed-d53c-434c-b5a2-e3b6bcbd8e67',
				courseId: 16,
				createdAt: '2023-10-27T17:41:35.144Z',
				updatedAt: '2023-10-27T17:43:44.443Z',
				features: [],
			},
			{
				id: 40,
				name: 'Первый модуль',
				enName: 'First module',
				type: 'free',
				price: 0,
				oldPrice: null,
				creditPrice: null,
				lengthInMonth: 0,
				videoUuid: 'dcff8a05-574f-45fa-8b2c-ee4093484f82',
				courseId: 16,
				createdAt: '2023-10-27T14:58:06.704Z',
				updatedAt: '2023-10-27T15:01:38.743Z',
				features: [],
			},
			{
				id: 41,
				name: 'Без наставника',
				enName: 'Without mentor',
				type: 'basic',
				price: 2999,
				oldPrice: 5000,
				creditPrice: null,
				lengthInMonth: 1,
				videoUuid: 'c8c11b58-7ebb-4156-8393-9f6c44f8aecf',
				courseId: 16,
				createdAt: '2023-10-27T15:01:31.009Z',
				updatedAt: '2023-10-27T17:38:39.304Z',
				features: [],
			},
		],
		avgRating: 4.9,
	},
];
