// let test = {
// 	achievements: [
// 		{
// 			alias: 'star',
// 			createdAt: '2024-01-21T22:20:07.000Z',
// 			event: 'UserUpdatedProfileEvent',
// 			icons: [Object],
// 			id: 2,
// 			necessaryProgress: 1,
// 			status: 'disabled',
// 			text: 'Заполнить профиль полностью',
// 			title: 'Звезда',
// 			updatedAt: '2024-01-21T22:20:08.000Z',
// 		},
// 		{
// 			alias: 'good-start',
// 			createdAt: '2024-01-22T00:43:11.000Z',
// 			event: 'LessonViewedEvent',
// 			icons: [Object],
// 			id: 5,
// 			necessaryProgress: 1,
// 			status: 'active',
// 			text: 'Начать 1 любой курс',
// 			title: 'Хороший старт',
// 			updatedAt: '2024-01-22T00:43:12.000Z',
// 		},
// 		{
// 			alias: 'welcome-to-the-club-buddy',
// 			createdAt: '2024-01-22T04:09:28.000Z',
// 			event: 'AddSubscriptionsToUserEvent',
// 			icons: [Object],
// 			id: 6,
// 			necessaryProgress: 1,
// 			status: 'disabled',
// 			text: 'Вступить в клуб, оформив подписку PurpleПлюс',
// 			title: 'В клубе',
// 			updatedAt: '2024-01-22T04:09:28.000Z',
// 		},
// 		{
// 			alias: 'first-purchase',
// 			createdAt: '2024-01-22T04:43:22.000Z',
// 			event: 'OrderWithMoneySuccessEvent',
// 			icons: [Object],
// 			id: 7,
// 			necessaryProgress: 1,
// 			status: 'active',
// 			text: 'Купить 1 любой курс',
// 			title: 'Первая покупка ',
// 			updatedAt: '2024-01-22T04:43:19.000Z',
// 		},
// 		{
// 			alias: 'three',
// 			createdAt: '2024-01-22T04:43:22.000Z',
// 			event: 'OrderWithMoneySuccessEvent',
// 			icons: [Object],
// 			id: 8,
// 			necessaryProgress: 3,
// 			status: 'active',
// 			text: 'Купить 3 любых курса',
// 			title: 'Нас трое',
// 			updatedAt: '2024-01-22T04:43:20.000Z',
// 		},
// 		{
// 			alias: 'pyatak',
// 			createdAt: '2024-01-22T04:43:23.000Z',
// 			event: 'OrderWithMoneySuccessEvent',
// 			icons: [Object],
// 			id: 9,
// 			necessaryProgress: 5,
// 			status: 'disabled',
// 			text: 'Купить 5 любых курсов',
// 			title: 'Пятак ',
// 			updatedAt: '2024-01-22T04:43:20.000Z',
// 		},
// 		{
// 			alias: 'schatlivchik',
// 			createdAt: '2024-01-22T04:43:24.000Z',
// 			event: 'OrderWithMoneySuccessEvent',
// 			icons: [Object],
// 			id: 10,
// 			necessaryProgress: 7,
// 			status: 'disabled',
// 			text: 'Купить 7 любых курсов',
// 			title: 'Счатливчик ',
// 			updatedAt: '2024-01-22T04:43:21.000Z',
// 		},
// 		{
// 			alias: 'billiard-man',
// 			createdAt: '2024-01-22T04:43:23.000Z',
// 			event: 'OrderWithMoneySuccessEvent',
// 			icons: [Object],
// 			id: 11,
// 			necessaryProgress: 9,
// 			status: 'disabled',
// 			text: 'Купить 9 любых курсов',
// 			title: 'Бильярдист ',
// 			updatedAt: '2024-01-22T04:43:21.000Z',
// 		},
// 		{
// 			alias: 'my-friend',
// 			createdAt: '2024-01-22T06:29:47.000Z',
// 			event: 'AppointmentEvent',
// 			icons: [Object],
// 			id: 12,
// 			necessaryProgress: 1,
// 			status: 'disabled',
// 			text: 'Начать курс с наставником',
// 			title: 'Мой друг',
// 			updatedAt: '2024-01-22T06:29:46.000Z',
// 		},
// 		{
// 			alias: 'first-finish',
// 			createdAt: '2024-01-22T07:04:39.000Z',
// 			event: 'CertificateIssuedEvent',
// 			icons: [Object],
// 			id: 14,
// 			necessaryProgress: 1,
// 			status: 'disabled',
// 			text: 'Пройти 1 курс на 100%',
// 			title: 'Первый финиш',
// 			updatedAt: '2024-01-22T07:04:40.000Z',
// 		},
// 		{
// 			alias: 'head-trick ',
// 			createdAt: '2024-01-22T07:04:41.000Z',
// 			event: 'CertificateIssuedEvent',
// 			icons: [Object],
// 			id: 15,
// 			necessaryProgress: 3,
// 			status: 'disabled',
// 			text: 'Пройти 3 курса на 100%',
// 			title: 'Head trick ',
// 			updatedAt: '2024-01-22T07:04:41.000Z',
// 		},
// 	],
// 	activity: null,
// 	profile: {
// 		chips: 0,
// 		cl_uid: null,
// 		click_id: null,
// 		createdAt: '2024-01-04T14:51:58.744Z',
// 		description: null,
// 		discordId: null,
// 		email: 'andrey.purple@rambler.ru',
// 		enFullName: null,
// 		gender: null,
// 		githubProfile: null,
// 		githubUrl: null,
// 		id: 692,
// 		inDiscord: false,
// 		inTelegram: false,
// 		interests: [],
// 		isService: false,
// 		jobTitle: null,
// 		name: 'Andrey',
// 		openAiTokenLimit: 0,
// 		openAiTokenUsages: 0,
// 		passwordHash: '$2a$10$fPxpprGGVyz6LMzy3TJ29eoJ4nQNb30ebcyxQ6jjaNDBoChW/rEEe',
// 		photo: null,
// 		pid: null,
// 		profileStatus: 'private',
// 		referrer: 'direct',
// 		restoreToken: null,
// 		role: 'student',
// 		skills: [],
// 		surname: null,
// 		telegramId: null,
// 		telegramNotifications: true,
// 		telegramUsername: null,
// 		updatedAt: '2024-01-04T14:51:58.744Z',
// 		utm_campaign: null,
// 		utm_content: null,
// 		utm_medium: null,
// 		utm_source: null,
// 		utm_term: null,
// 	},
// };
